#version: '3.8'

services:
  postgresDB:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgres/data
    networks:
      - my-network

  app:
    depends_on:
      - postgresDB
    build: ./
    container_name: vuttr-app
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes: 
  pgdata:
    external: true
    name: pgdata