#version: '3.8'

services:
  postgresDB:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgres/data
  app:
    depends_on:
      - postgresdb
    build:
      context: .
    container_name: vuttr-app
    restart: unless-stopped
    ports:
      - 3000:3000

volumes: 
  pgdata: