const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./api/routes/toolsRoutes.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "VUTTR API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
}


swaggerAutogen(outputFile, endpointsFiles, doc)